---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- name: objective
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Objective
- name: status
  type: select
  default: []
  config:
    required: false
    options:
    - Planning
    - In-Progress
    - Complete
    - Active
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Status
pages:
- projects/Food Security/introduction.md
- projects/Online Store/introduction.md
- projects/Recycling Depot/introduction.md
