---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- name: members
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: 
      file: 
      path: 
  label: Members
- name: objective
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Objective
- name: status
  type: select
  default: []
  config:
    required: false
    options:
    - Planning
    - In-Progress
    - Complete
    - Active
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Status
pages:
- projects/Food Security/introduction.md
